export const UK_FRESHWATER_SPECIES = [
  { value: "arctic_char", label: "Arctic Char" },
  { value: "atlantic_salmon", label: "Atlantic Salmon" },
  { value: "barbel", label: "Barbel" },
  { value: "bleak", label: "Bleak" },
  { value: "bream", label: "Bream (Unspecified)" },
  { value: "common_bream", label: "Common Bream" },
  { value: "silver_bream", label: "Silver Bream" },
  { value: "brown_trout", label: "Brown Trout" },
  { value: "trout", label: "Trout (Unspecified)" },
  { value: "bullhead", label: "Bullhead" },
  { value: "carp", label: "Carp (Unspecified)" },
  { value: "common_carp", label: "Common Carp" },
  { value: "mirror_carp", label: "Mirror Carp" },
  { value: "leather_carp", label: "Leather Carp" },
  { value: "ghost_carp", label: "Ghost Carp" },
  { value: "grass_carp", label: "Grass Carp" },
  { value: "crucian_carp", label: "Crucian Carp" },
  { value: "wels_catfish", label: "Wels Catfish" },
  { value: "catfish", label: "Catfish (Unspecified)" },
  { value: "chub", label: "Chub" },
  { value: "dace", label: "Dace" },
  { value: "european_eel", label: "European Eel" },
  { value: "ferox_trout", label: "Ferox Trout" },
  { value: "golden_orfe", label: "Golden Orfe" },
  { value: "grayling", label: "Grayling" },
  { value: "gudgeon", label: "Gudgeon" },
  { value: "ide", label: "Ide" },
  { value: "lamprey", label: "Lamprey" },
  { value: "perch", label: "Perch" },
  { value: "pike", label: "Pike" },
  { value: "powan", label: "Powan" },
  { value: "rainbow_trout", label: "Rainbow Trout" },
  { value: "roach", label: "Roach" },
  { value: "rudd", label: "Rudd" },
  { value: "sea_trout", label: "Sea Trout" },
  { value: "smelt", label: "Smelt" },
  { value: "stickleback", label: "Stickleback" },
  { value: "stone_loach", label: "Stone Loach" },
  { value: "sturgeon", label: "Sturgeon" },
  { value: "tench", label: "Tench" },
  { value: "zander", label: "Zander" },
] as const;

const speciesLabelMap = new Map(UK_FRESHWATER_SPECIES.map((species) => [species.value, species.label]));

const toTitleCase = (value: string) =>
  value
    .split(" ")
    .map((word) => (word ? word.charAt(0).toUpperCase() + word.slice(1).toLowerCase() : ""))
    .join(" ");

export const getFreshwaterSpeciesLabel = (value: string | null | undefined) => {
  if (!value) return "";
  return speciesLabelMap.get(value) ?? value
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
};

export const UK_FISHERIES = [
  "Anglers Paradise, Devon",
  "Avington Trout Fishery, Hampshire",
  "Badshot Lea Big Pond, Surrey",
  "Barston Lakes, West Midlands",
  "Bewl Water, Kent",
  "Blagdon Lake, Somerset",
  "Bluebell Lakes, Northamptonshire",
  "Boddington Reservoir, Northamptonshire",
  "Bratton Water, Devon",
  "Broadwater Lake, Surrey",
  "Brotherswood Lakes, West Sussex",
  "Burton Springs, Somerset",
  "Bury Hill Fisheries, Surrey",
  "Caldicot Castle Lake, Monmouthshire",
  "Carsington Water, Derbyshire",
  "Chew Valley Lake, Somerset",
  "Chigboro Fisheries, Essex",
  "Cholmondeley Castle Lakes, Cheshire",
  "Church Lake (Chapel Baits), Kent",
  "Clattercote Reservoir, Oxfordshire",
  "Clywedog Reservoir, Powys",
  "Coed Ty Mawr Fishery, Wrexham",
  "Colwick Country Park, Nottinghamshire",
  "Colwick Park Trout Lake, Nottinghamshire",
  "Cotswold Water Park, Gloucestershire",
  "Creslow Pools, Buckinghamshire",
  "Docklow Pools, Herefordshire",
  "Drayton Reservoir, Northamptonshire",
  "Earith Lakes, Cambridgeshire",
  "Eden Springs Trout Fishery, Cumbria",
  "Elinor Trout Fishery, Northamptonshire",
  "Elphicks Fisheries, Kent",
  "Esthwaite Water Trout Fishery, Cumbria",
  "Eyebrook Reservoir, Leicestershire",
  "Farmoor Reservoir, Oxfordshire",
  "Farnham Flint Lakes, Surrey",
  "Farlows Lake, Buckinghamshire",
  "Forest Lane Fisheries, Cheshire",
  "Frensham Great Pond, Surrey",
  "Frensham Small Pond, Surrey",
  "Furnace Mill Fisheries, Worcestershire",
  "Gailey Reservoir, Staffordshire",
  "Garnffrwd Fishery, Carmarthenshire",
  "Gingerbread Lake, Bedfordshire",
  "Gold Valley Lakes, Hampshire",
  "Grafham Water, Cambridgeshire",
  "Grebe Lake, Bedfordshire",
  "Hanningfield Reservoir, Essex",
  "Hayfield Lakes, South Yorkshire",
  "Holgan Farm, Pembrokeshire",
  "Horseshoe Lake, Gloucestershire",
  "Kilnsey Park Estate, North Yorkshire",
  "Kingfisher Trout Lake, Devon",
  "Kingsbury Water Park, Warwickshire",
  "Ladybower Fisheries, Derbyshire",
  "Lakelands Trout Fishery, Cheshire",
  "Linear Fisheries - Brasenose 1, Oxfordshire",
  "Linear Fisheries - Brasenose 2, Oxfordshire",
  "Linear Fisheries - Hardwick & Smiths, Oxfordshire",
  "Linear Fisheries - Hunts Corner, Oxfordshire",
  "Linear Fisheries - Oxlease Lake, Oxfordshire",
  "Linear Fisheries - St. Johns Lake, Oxfordshire",
  "Lockwood Beck Reservoir, North Yorkshire",
  "Llyn Brenig, Denbighshire",
  "Llyn Clywedog, Powys",
  "Llyn Trawsfynydd, Gwynedd",
  "Lodge Farm Fisheries, Northamptonshire",
  "Loch Leven, Perth and Kinross",
  "Loch Awe, Argyll and Bute",
  "Loch Lomond, West Dunbartonshire",
  "Manor Farm Lakes, Bedfordshire",
  "Meadowlands Fishery, Warwickshire",
  "Milton Pools Fishery, Oxfordshire",
  "Monk Lakes, Kent",
  "Old Bury Hill Lake, Surrey",
  "Partridge Lakes Fishery, Cheshire",
  "Portsmouth Watersports Centre Lake, Hampshire",
  "Redmire Pool, Herefordshire",
  "Ringstead Grange, Northamptonshire",
  "Rookery Waters, Cambridgeshire",
  "Rutland Water, Rutland",
  "Staunton Harold Reservoir, Leicestershire",
  "Stocks Reservoir, Lancashire",
  "Stour Valley Lakes, Dorset",
  "Sutton Lake, Shropshire",
  "Thornham Fishery, Norfolk",
  "Todber Manor Fisheries, Dorset",
  "Upper Tamar Lake, Cornwall",
  "Walthamstow Reservoirs, London",
  "Watermark Lakes, Gloucestershire",
  "Weston Pools, Shropshire",
  "Willow Park Fishery, Hampshire",
  "Willowgate Fishery, Perthshire",
  "Wingham Fisheries, Kent",
  "Wraysbury 1 South Lake, Berkshire",
  "Wraysbury No. 1, Berkshire",
] as const;

export const normalizeVenueName = (input: string) => {
  if (!input) return "";
  const trimmed = input.trim().replace(/\s+/g, " ");
  const lower = trimmed.toLowerCase();
  const match = UK_FISHERIES.find((fishery) => fishery.toLowerCase() === lower);
  if (match) {
    return match;
  }
  return toTitleCase(trimmed);
};
