import { getPublicAssetUrl } from "@/lib/storage";
import type { CatchRow, Venue, VenuePhoto } from "./types";
import {
  getDisplayPriceFrom,
  humanizeSpecies,
  normalizeTag,
  sanitizeCatchTitle,
} from "./utils";

type BuildVenueDetailViewModelInput = {
  venue: Venue;
  topCatches: CatchRow[];
  recentCatches: CatchRow[];
  photos: VenuePhoto[];
  userId?: string | null;
  isAdmin: boolean;
  isOwner: boolean;
  avgRating: number | null;
  ratingCount: number | null;
  userRating: number | null;
  ratingLoading: boolean;
  lastKnownAvg: number | null;
  lastKnownCount: number | null;
  heroIndex: number;
  heroHasImage: boolean;
  upcomingEventsCount: number;
  pastEventsCount: number;
};

export type VenueDetailViewModel = {
  ticketType: string;
  priceFrom: string;
  websiteUrl: string;
  bookingUrl: string;
  contactPhone: string;
  totalCatches: number;
  recentWindow: number;
  displayPriceFrom: string;
  hasPlanContent: boolean;
  facilitiesList: string[];
  bestForTags: string[];
  pricingLines: string[];
  heroTagline: string;
  aboutText: string;
  heroImages: string[];
  activeHeroImage: string | null;
  hasHeroCarousel: boolean;
  carouselItems: { url: string; alt: string }[];
  carouselLabel: string;
  showStickyActions: boolean;
  hasEvents: boolean;
  activeAnglers: number;
  recordWeightLabel: string | null;
  recordSpeciesLabel: string | null;
  topSpeciesLabel: string | null;
  featuredCatchTitle: string | null;
  primaryCtaUrl: string;
  secondaryCtaUrl: string;
  secondaryCtaLabel: string;
  ratingSummaryText: string;
  displayAvg: string | null;
  displayCount: number | null | undefined;
  hasRatings: boolean;
  showNoRatings: boolean;
  scrimClass: string;
  mapsUrl: string;
  mapEmbedUrl: string | null;
  viewAllCount: number;
  showAboutAdminHint: boolean;
};

export const buildVenueDetailViewModel = (
  input: BuildVenueDetailViewModelInput
): VenueDetailViewModel => {
  const {
    venue,
    topCatches,
    recentCatches,
    photos,
    userId,
    isAdmin,
    isOwner,
    avgRating,
    ratingCount,
    ratingLoading,
    lastKnownAvg,
    lastKnownCount,
    heroIndex,
    heroHasImage,
    upcomingEventsCount,
    pastEventsCount,
  } = input;

  const ticketType = venue.ticket_type?.trim() ?? "";
  const priceFrom = venue.price_from?.trim() ?? "";
  const websiteUrl = venue.website_url?.trim() ?? "";
  const bookingUrl = venue.booking_url?.trim() ?? "";
  const contactPhone = venue.contact_phone?.trim() ?? "";
  const totalCatches = venue.total_catches ?? 0;
  const recentWindow = venue.recent_catches_30d ?? 0;
  const facilities = (venue.facilities ?? []).filter(Boolean);
  const bestForTags = (venue.best_for_tags ?? []).filter(Boolean);
  const hasTicketsContent =
    !!ticketType ||
    !!priceFrom ||
    !!websiteUrl ||
    !!bookingUrl ||
    !!contactPhone;
  const hasFacilities = facilities.length > 0;
  const bestForSet = new Set(bestForTags.map((tag) => normalizeTag(tag)));
  const filteredFacilities = facilities.filter(
    (item) => !bestForSet.has(normalizeTag(item))
  );
  const displayPriceFrom = getDisplayPriceFrom(venue.price_from);
  const hasPlanContent = hasTicketsContent || hasFacilities || bestForTags.length > 0;
  const facilitiesList =
    filteredFacilities.length > 0 ? filteredFacilities : facilities;
  const pricingLines = [displayPriceFrom, ticketType].filter(
    (line): line is string => Boolean(line)
  );

  const heroTagline =
    venue.short_tagline ||
    (venue.description
      ? `${venue.description.split(". ").slice(0, 2).join(". ")}${
          venue.description.includes(".") ? "." : ""
        }`
      : "") ||
    "Details autogenerated from our venue list. Community catches coming soon.";
  const aboutText = venue.description || heroTagline || "Details coming soon.";
  const heroImages = photos
    .map((photo) => getPublicAssetUrl(photo.image_path))
    .filter((url): url is string => Boolean(url));
  const activeHeroImage = heroImages[heroIndex] ?? null;
  const hasHeroCarousel = heroImages.length > 1;
  const venueCarouselItems = heroImages.map((url, index) => ({
    url,
    alt: `${venue.name ?? "Venue"} photo ${index + 1}`,
  }));
  const fallbackCatchItems = (() => {
    const items: { url: string; alt: string }[] = [];
    const seen = new Set<string>();
    const candidates = [...recentCatches, ...topCatches];
    for (const catchItem of candidates) {
      if (!catchItem.image_url) continue;
      if (seen.has(catchItem.image_url)) continue;
      seen.add(catchItem.image_url);
      items.push({
        url: catchItem.image_url,
        alt: sanitizeCatchTitle(catchItem.title) ?? "Community catch",
      });
      if (items.length >= 12) break;
    }
    return items;
  })();
  const carouselItems = (
    venueCarouselItems.length > 0 ? venueCarouselItems : fallbackCatchItems
  ).slice(0, 8);
  const carouselLabel = "Venue photo gallery";
  const featuredCatch = topCatches[0];
  const recordWeightLabel = featuredCatch?.weight
    ? `${featuredCatch.weight}${
        featuredCatch.weight_unit === "kg" ? "kg" : "lb"
      }`
    : venue.headline_pb_weight
    ? `${venue.headline_pb_weight}${
        venue.headline_pb_unit === "kg" ? "kg" : "lb"
      }`
    : null;
  const recordSpeciesLabel = featuredCatch?.species || venue.headline_pb_species;
  const featuredCatchTitle = sanitizeCatchTitle(featuredCatch?.title);
  const topSpeciesRaw = (venue.top_species ?? []).filter(Boolean)[0];
  const topSpeciesLabel = topSpeciesRaw ? humanizeSpecies(topSpeciesRaw) : null;

  const showStickyActions = !!userId && !isAdmin;
  const hasEvents = upcomingEventsCount > 0 || pastEventsCount > 0;
  const activeAnglers = topCatches.length;
  const primaryCtaUrl = bookingUrl || websiteUrl;
  const secondaryCtaUrl = websiteUrl;
  const secondaryCtaLabel = displayPriceFrom ? "View Prices" : "Visit Website";

  const hasResolvedRatingCount =
    ratingCount !== null && ratingCount !== undefined;
  const formattedAvg = avgRating ? Number(avgRating).toFixed(1) : null;
  const displayAvg =
    ratingLoading && lastKnownAvg !== null
      ? lastKnownAvg.toFixed(1)
      : formattedAvg ?? (lastKnownAvg !== null ? lastKnownAvg.toFixed(1) : null);
  const displayCount =
    ratingLoading && lastKnownCount !== null
      ? lastKnownCount
      : hasResolvedRatingCount
      ? ratingCount
      : lastKnownCount;
  const hasRatings =
    (displayCount ?? 0) > 0 && displayAvg !== null && displayAvg !== undefined;
  const showNoRatings =
    hasResolvedRatingCount && (ratingCount ?? 0) === 0 && !ratingLoading;
  const ratingSummaryText =
    hasRatings && displayAvg
      ? `${displayAvg} • ${displayCount} rating${
          (displayCount ?? 0) === 1 ? "" : "s"
        }`
      : showNoRatings
      ? "0.0 • 0 ratings"
      : "Ratings loading…";

  const scrimClass = heroHasImage
    ? "bg-gradient-to-br from-slate-950/45 via-slate-950/55 to-slate-900/70"
    : "bg-gradient-to-br from-slate-950/60 via-slate-950/55 to-slate-900/65";

  const mapsUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(
    venue.name
  )}`;
  const mapEmbedUrl = venue.location
    ? `https://www.google.com/maps?q=${encodeURIComponent(
        `${venue.name} ${venue.location ?? ""}`
      )}&output=embed`
    : null;

  const viewAllCount = totalCatches > 0 ? totalCatches : recentCatches.length;
  const showAboutAdminHint =
    !(venue.description || heroTagline) && (isAdmin || isOwner);

  return {
    ticketType,
    priceFrom,
    websiteUrl,
    bookingUrl,
    contactPhone,
    totalCatches,
    recentWindow,
    displayPriceFrom,
    hasPlanContent,
    facilitiesList,
    bestForTags,
    pricingLines,
    heroTagline,
    aboutText,
    heroImages,
    activeHeroImage,
    hasHeroCarousel,
    carouselItems,
    carouselLabel,
    showStickyActions,
    hasEvents,
    activeAnglers,
    recordWeightLabel,
    recordSpeciesLabel,
    topSpeciesLabel,
    featuredCatchTitle,
    primaryCtaUrl,
    secondaryCtaUrl,
    secondaryCtaLabel,
    ratingSummaryText,
    displayAvg,
    displayCount,
    hasRatings,
    showNoRatings,
    scrimClass,
    mapsUrl,
    mapEmbedUrl,
    viewAllCount,
    showAboutAdminHint,
  };
};
